# Generated by Django 4.1 on 2022-09-06 19:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_id', models.CharField(max_length=36)),
                ('event_settings', models.TextField(blank=True)),
                ('location_name', models.CharField(max_length=128)),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('number_of_attendees', models.IntegerField()),
                ('event_datetime', models.DateTimeField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='invited', max_length=100)),
                ('invite_idx', models.IntegerField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
