# Generated by Django 4.1 on 2022-09-07 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_remove_invitation_invite_idx_alter_invitation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('user', 'event')},
        ),
    ]
