# Generated by Django 4.1 on 2022-08-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
