# Generated by Django 4.1 on 2022-09-01 21:09

from django.db import migrations, models
import swizzlebackend.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_auth', '0003_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.FileField(blank=True, storage=swizzlebackend.storage_backends.PrivateMediaStorage(), upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
