# Generated by Django 4.1 on 2022-09-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_auth', '0004_alter_myuser_avatar_alter_myuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatars'),
        ),
    ]
